package loader

import (
	"mbfs/go-mbfs/plugin"
	pluginbadgerds "mbfs/go-mbfs/plugin/plugins/badgerds"
	pluginflatfs "mbfs/go-mbfs/plugin/plugins/flatfs"
	pluginipldgit "mbfs/go-mbfs/plugin/plugins/git"
	pluginlevelds "mbfs/go-mbfs/plugin/plugins/levelds"
)

// DO NOT EDIT THIS FILE
// This file is being generated as part of plugin build process
// To change it, modify the plugin/loader/preload.sh

var preloadPlugins = []plugin.Plugin{
	pluginipldgit.Plugins[0],
	pluginbadgerds.Plugins[0],
	pluginflatfs.Plugins[0],
	pluginlevelds.Plugins[0],
}
